export const Component = {
  Application: Symbol.for('Application'),
  LoggerInterface: Symbol.for('LoggerInterface'),
  ConfigInterface: Symbol.for('ConfigInterface'),
  DatabaseInterface: Symbol.for('DatabaseInterface'),
  UserServiceInterface: Symbol.for('UserServiceInterface'),
  MovieServiceInterface: Symbol.for('MovieServiceInterface'),
  WatchLaterServiceInterface: Symbol.for('WatchLaterServiceInterface'),
  UserModel: Symbol.for('UserModel'),
  MovieModel: Symbol.for('MovieModel'),
  WatchLaterModel: Symbol.for('WatchLaterModel'),
  CommentModel: Symbol.for('CommentModel'),
  CommentServiceInterface: Symbol.for('CommentServiceInterface'),
  UserController: Symbol.for('UserController'),
  MovieController: Symbol.for('MovieController'),
  ExceptionFilterInterface: Symbol.for('ExceptionFilterInterface'),
} as const;
