export type MockData = {
  titles: string[];
  descriptions: string[];
  publicationDates: string[];
  genres: string[];
  releaseYears: number[];
  ratings: number[];
  videoPreviewUris: string[];
  videoUris: string[];
  casts: string[];
  producers: string[];
  durations: number[];
  commentAmounts: number[];
  userNames: string[];
  userAvatarUris: string[];
  userEmails: string[];
  posterUris: string[];
  backgroundImageUris: string[];
  backgroundColors: string[];
};
